version: "3"

services:
  cppapp1:
    container_name: cppapp1
    privileged: true
    stdin_open: true
    tty: true
    build: ./docker
    volumes:
      - ./src:/home/src
    network_mode: "none"
